author = Artur Tarassow
email = atecon@posteo.de
version = 0.1
date = 2020-05-08
description = Retrieve list of holiday series
tags = C81
min-version = 2020a
public = holidays get_list_of_holidays get_names_of_holidays print_names_of_holidays
data-requirement = needs-time-series-data
help = holidays_help.txt
sample-script = holidays_sample.inp
depends = string_utils
