author = Artur Tarassow
email = atecon@posteo.de
version = 0.2
date = 2021-03-22
description = Retrieve list of holiday series
tags = C81
min-version = 2020c
public = holidays get_list_of_holidays get_names_of_holidays print_names_of_holidays
help = holidays_help.txt
sample-script = holidays_sample.inp
depends = string_utils
