author = Artur Tarassow
email = atecon@posteo.de
version = 0.1
date = 2020-05-08
description = Retrieve list of holiday series
tags = C81
min-version = 2020a
public = holidays get_list_of_holidays
help = holidays_help.txt
sample-script = holidays_sample.inp
